<?php

namespace Database\Seeders;

use App\Models\Product;
use App\Models\Category;
use App\Models\Supplier;
use App\Models\ProductImage;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class CosmeticProductsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Obtener categorías y proveedores existentes
        $cuidadoPiel = Category::where('category', 'Cuidado de la Piel')->first();
        $maquillaje = Category::where('category', 'Maquillaje')->first();
        $cabello = Category::where('category', 'Cuidado del Cabello')->first();
        $fragancias = Category::where('category', 'Fragancias')->first();
        $accesorios = Category::where('category', 'Accesorios de Belleza')->first();
        $higiene = Category::where('category', 'Higiene Personal')->first();
        $natural = Category::where('category', 'Cosmética Natural')->first();

        $supplier1 = Supplier::first();
        $supplier2 = Supplier::skip(1)->first();
        $supplier3 = Supplier::skip(2)->first();

        $products = [
            // CUIDADO DE LA PIEL
            [
                'title' => 'Crema Facial Anti-Edad con Retinol',
                'description' => 'Crema facial avanzada con retinol puro al 2.5% y péptidos. Reduce visiblemente las arrugas, líneas de expresión y manchas oscuras. Mejora la elasticidad y firmeza de la piel. Fórmula no comedogénica ideal para todo tipo de piel. Aplicar por la noche sobre la piel limpia.',
                'category_id' => $cuidadoPiel?->id ?? 1,
                'supplier_id' => $supplier1?->id ?? 1,
                'cost' => 25.00,
                'sellingprice' => 45.00,
                'discount' => 10,
                'price' => 40.50,
                'qty' => 30,
                'total_cost' => 750.00,
                'total_price' => 1215.00,
                'published' => 1,
            ],
            [
                'title' => 'Sérum Vitamina C + Ácido Hialurónico',
                'description' => 'Sérum facial iluminador con 20% de vitamina C estabilizada y ácido hialurónico. Aclara la piel, reduce manchas y proporciona hidratación intensa. Protege contra el daño de los radicales libres. Textura ligera de rápida absorción. Ideal para uso matutino antes del protector solar.',
                'category_id' => $cuidadoPiel?->id ?? 1,
                'supplier_id' => $supplier2?->id ?? 2,
                'cost' => 18.00,
                'sellingprice' => 35.00,
                'discount' => 0,
                'price' => 35.00,
                'qty' => 25,
                'total_cost' => 450.00,
                'total_price' => 875.00,
                'published' => 1,
            ],
            [
                'title' => 'Mascarilla Facial de Arcilla Purificante',
                'description' => 'Mascarilla facial con arcilla verde y carbón activado. Elimina impurezas, exfolia suavemente y reduce el tamaño de los poros. Controla el exceso de grasa sin resecar la piel. Contiene extracto de té verde y aloe vera para calmar. Aplicar 1-2 veces por semana.',
                'category_id' => $cuidadoPiel?->id ?? 1,
                'supplier_id' => $supplier1?->id ?? 1,
                'cost' => 12.00,
                'sellingprice' => 22.00,
                'discount' => 5,
                'price' => 20.90,
                'qty' => 40,
                'total_cost' => 480.00,
                'total_price' => 836.00,
                'published' => 1,
            ],
            [
                'title' => 'Protector Solar SPF 50+ Facial',
                'description' => 'Protector solar de amplio espectro SPF 50+ especialmente formulado para el rostro. Protección UVA/UVB con filtros físicos y químicos. Textura ligera, no grasa, no comedogénica. Resistente al agua hasta 80 minutos. Ideal para uso diario, incluso bajo maquillaje.',
                'category_id' => $cuidadoPiel?->id ?? 1,
                'supplier_id' => $supplier3?->id ?? 3,
                'cost' => 15.00,
                'sellingprice' => 28.00,
                'discount' => 0,
                'price' => 28.00,
                'qty' => 35,
                'total_cost' => 525.00,
                'total_price' => 980.00,
                'published' => 1,
            ],
            [
                'title' => 'Crema Contorno de Ojos Antiojeras',
                'description' => 'Crema especializada para el contorno de ojos con cafeína, péptidos y vitamina K. Reduce visiblemente las ojeras, bolsas e hinchazón. Hidrata intensamente la delicada zona del contorno. Aplicar con toques suaves mañana y noche. Envase con aplicador de metal para efecto refrescante.',
                'category_id' => $cuidadoPiel?->id ?? 1,
                'supplier_id' => $supplier2?->id ?? 2,
                'cost' => 20.00,
                'sellingprice' => 38.00,
                'discount' => 8,
                'price' => 34.96,
                'qty' => 28,
                'total_cost' => 560.00,
                'total_price' => 978.88,
                'published' => 1,
            ],

            // MAQUILLAJE
            [
                'title' => 'Base de Maquillaje Líquida Full Coverage',
                'description' => 'Base de maquillaje líquida de alta cobertura y acabado mate. Cubre imperfecciones, manchas y cicatrices. Fórmula de larga duración hasta 16 horas. Resistente al sudor y al agua. Disponible en 12 tonos. Ideal para pieles mixtas y grasas.',
                'category_id' => $maquillaje?->id ?? 2,
                'supplier_id' => $supplier1?->id ?? 1,
                'cost' => 22.00,
                'sellingprice' => 42.00,
                'discount' => 12,
                'price' => 36.96,
                'qty' => 20,
                'total_cost' => 440.00,
                'total_price' => 739.20,
                'published' => 1,
            ],
            [
                'title' => 'Paleta de Sombras 12 Colores',
                'description' => 'Paleta de sombras para ojos con 12 tonos altamente pigmentados. Incluye colores mates y con brillo. Fácil de difuminar y de larga duración. Ideal para crear looks desde naturales hasta dramáticos. Incluye espejo y aplicador dual.',
                'category_id' => $maquillaje?->id ?? 2,
                'supplier_id' => $supplier2?->id ?? 2,
                'cost' => 28.00,
                'sellingprice' => 55.00,
                'discount' => 15,
                'price' => 46.75,
                'qty' => 15,
                'total_cost' => 420.00,
                'total_price' => 701.25,
                'published' => 1,
            ],
            [
                'title' => 'Labial Líquido Matte de Larga Duración',
                'description' => 'Labial líquido con acabado mate y larga duración. No se transfiere, no se seca ni agrieta. Fórmula hidratante con vitamina E. Disponible en 8 tonos vibrantes. Aplicación precisa con aplicador tipo doe-foot. Duración hasta 8 horas.',
                'category_id' => $maquillaje?->id ?? 2,
                'supplier_id' => $supplier1?->id ?? 1,
                'cost' => 14.00,
                'sellingprice' => 26.00,
                'discount' => 10,
                'price' => 23.40,
                'qty' => 50,
                'total_cost' => 700.00,
                'total_price' => 1170.00,
                'published' => 1,
            ],
            [
                'title' => 'Máscara de Pestañas Voluminizadora',
                'description' => 'Máscara de pestañas con cepillo curvo que añade volumen y longitud. Fórmula resistente al agua que no se corre. Separador de pestañas integrado. Aplicación fácil sin grumos. Efecto dramático y profesional. Ideal para uso diario y ocasiones especiales.',
                'category_id' => $maquillaje?->id ?? 2,
                'supplier_id' => $supplier3?->id ?? 3,
                'cost' => 10.00,
                'sellingprice' => 18.00,
                'discount' => 5,
                'price' => 17.10,
                'qty' => 60,
                'total_cost' => 600.00,
                'total_price' => 1026.00,
                'published' => 1,
            ],
            [
                'title' => 'Corrector Crema Alta Cobertura',
                'description' => 'Corrector cremoso de alta cobertura para ojeras, manchas e imperfecciones. Textura cremosa que no se agrieta. Fácil de difuminar y mezclar. Disponible en 6 tonos. Fórmula hidratante con ácido hialurónico. Duración todo el día.',
                'category_id' => $maquillaje?->id ?? 2,
                'supplier_id' => $supplier2?->id ?? 2,
                'cost' => 16.00,
                'sellingprice' => 30.00,
                'discount' => 0,
                'price' => 30.00,
                'qty' => 35,
                'total_cost' => 560.00,
                'total_price' => 1050.00,
                'published' => 1,
            ],

            // CUIDADO DEL CABELLO
            [
                'title' => 'Shampoo Reparador con Keratina',
                'description' => 'Shampoo reparador con keratina y proteínas de seda. Repara cabello dañado, quebradizo y con puntas abiertas. Restaura la suavidad y brillo natural. Fórmula sin sulfatos. Ideal para cabello teñido y tratado químicamente. 400ml.',
                'category_id' => $cabello?->id ?? 3,
                'supplier_id' => $supplier1?->id ?? 1,
                'cost' => 12.00,
                'sellingprice' => 24.00,
                'discount' => 8,
                'price' => 22.08,
                'qty' => 40,
                'total_cost' => 480.00,
                'total_price' => 883.20,
                'published' => 1,
            ],
            [
                'title' => 'Acondicionador Hidratante Intenso',
                'description' => 'Acondicionador ultra hidratante con aceite de argán y manteca de karité. Nutre profundamente el cabello seco y dañado. Reduce el frizz y facilita el peinado. Deja el cabello suave, sedoso y manejable. Aplicar de medios a puntas. 400ml.',
                'category_id' => $cabello?->id ?? 3,
                'supplier_id' => $supplier2?->id ?? 2,
                'cost' => 13.00,
                'sellingprice' => 25.00,
                'discount' => 0,
                'price' => 25.00,
                'qty' => 38,
                'total_cost' => 494.00,
                'total_price' => 950.00,
                'published' => 1,
            ],
            [
                'title' => 'Mascarilla Capilar Reparadora',
                'description' => 'Mascarilla capilar reparadora con aceite de coco y miel. Tratamiento intensivo para cabello muy dañado. Restaura la elasticidad y fuerza del cabello. Aplicar una vez por semana dejando actuar 10-15 minutos. Resultados visibles desde el primer uso. 250ml.',
                'category_id' => $cabello?->id ?? 3,
                'supplier_id' => $supplier3?->id ?? 3,
                'cost' => 18.00,
                'sellingprice' => 32.00,
                'discount' => 10,
                'price' => 28.80,
                'qty' => 30,
                'total_cost' => 540.00,
                'total_price' => 864.00,
                'published' => 1,
            ],
            [
                'title' => 'Aceite Capilar Multiusos',
                'description' => 'Aceite capilar con argania y jojoba. Hidrata, nutre y sella las puntas. Reduce el frizz y añade brillo. Puede usarse en cabello seco o húmedo. También como tratamiento pre-shampoo. No engrasa, absorción rápida. 100ml.',
                'category_id' => $cabello?->id ?? 3,
                'supplier_id' => $supplier1?->id ?? 1,
                'cost' => 20.00,
                'sellingprice' => 38.00,
                'discount' => 5,
                'price' => 36.10,
                'qty' => 25,
                'total_cost' => 500.00,
                'total_price' => 902.50,
                'published' => 1,
            ],

            // FRAGANCIAS
            [
                'title' => 'Perfume Mujer - Eau de Parfum 50ml',
                'description' => 'Perfume femenino con notas florales y frutales. Apertura con bergamota y fresa. Corazón de rosa y jazmín. Base de sándalo y vainilla. Duración hasta 8 horas. Fragancia elegante y sofisticada. Presentación en frasco de vidrio con pulverizador.',
                'category_id' => $fragancias?->id ?? 4,
                'supplier_id' => $supplier2?->id ?? 2,
                'cost' => 35.00,
                'sellingprice' => 75.00,
                'discount' => 15,
                'price' => 63.75,
                'qty' => 20,
                'total_cost' => 700.00,
                'total_price' => 1275.00,
                'published' => 1,
            ],
            [
                'title' => 'Perfume Hombre - Eau de Toilette 100ml',
                'description' => 'Fragancia masculina fresca y moderna. Notas de cítricos, especias y maderas. Apertura con limón y pimienta. Corazón de lavanda y geranio. Base de cedro y ámbar. Ideal para uso diario. Duración 6-8 horas.',
                'category_id' => $fragancias?->id ?? 4,
                'supplier_id' => $supplier1?->id ?? 1,
                'cost' => 40.00,
                'sellingprice' => 85.00,
                'discount' => 12,
                'price' => 74.80,
                'qty' => 18,
                'total_cost' => 720.00,
                'total_price' => 1346.40,
                'published' => 1,
            ],
            [
                'title' => 'Colonia Unisex - Agua Fresca 200ml',
                'description' => 'Colonia unisex con notas acuáticas y cítricas. Fragancia ligera y refrescante. Perfecta para uso diario y deportivo. Notas de limón, menta y algas marinas. Ideal para todas las edades. Presentación económica en formato grande.',
                'category_id' => $fragancias?->id ?? 4,
                'supplier_id' => $supplier3?->id ?? 3,
                'cost' => 15.00,
                'sellingprice' => 28.00,
                'discount' => 0,
                'price' => 28.00,
                'qty' => 45,
                'total_cost' => 675.00,
                'total_price' => 1260.00,
                'published' => 1,
            ],

            // ACCESORIOS DE BELLEZA
            [
                'title' => 'Set de Brochas Profesionales 12 Piezas',
                'description' => 'Set completo de brochas de maquillaje profesionales. Cerdas sintéticas suaves y densas. Incluye brochas para base, polvo, rubor, sombras, delineador y más. Mangos ergonómicos. Estuche protector incluido. Ideal para principiantes y profesionales.',
                'category_id' => $accesorios?->id ?? 5,
                'supplier_id' => $supplier1?->id ?? 1,
                'cost' => 30.00,
                'sellingprice' => 58.00,
                'discount' => 18,
                'price' => 47.56,
                'qty' => 15,
                'total_cost' => 450.00,
                'total_price' => 713.40,
                'published' => 1,
            ],
            [
                'title' => 'Esponja Beauty Blender Original',
                'description' => 'Esponja de maquillaje en forma de huevo. Aplicación impecable de base y corrector. Se usa húmeda para un acabado natural. Material no poroso que no absorbe producto. Fácil de limpiar. Color rosa clásico. Incluye estuche de viaje.',
                'category_id' => $accesorios?->id ?? 5,
                'supplier_id' => $supplier2?->id ?? 2,
                'cost' => 18.00,
                'sellingprice' => 35.00,
                'discount' => 10,
                'price' => 31.50,
                'qty' => 30,
                'total_cost' => 540.00,
                'total_price' => 945.00,
                'published' => 1,
            ],
            [
                'title' => 'Espejo de Aumento con Luz LED',
                'description' => 'Espejo de aumento 10x con iluminación LED ajustable. 3 niveles de brillo. Carga USB. Base estable y diseño moderno. Ideal para aplicación precisa de maquillaje. Incluye espejo normal en el reverso. Perfecto para el tocador.',
                'category_id' => $accesorios?->id ?? 5,
                'supplier_id' => $supplier3?->id ?? 3,
                'cost' => 45.00,
                'sellingprice' => 85.00,
                'discount' => 20,
                'price' => 68.00,
                'qty' => 12,
                'total_cost' => 540.00,
                'total_price' => 816.00,
                'published' => 1,
            ],

            // HIGIENE PERSONAL
            [
                'title' => 'Jabón Líquido Hidratante con Avena',
                'description' => 'Jabón líquido para manos y cuerpo con extracto de avena y glicerina. Limpia suavemente sin resecar. Hidrata y protege la barrera cutánea. Fórmula hipoalergénica. Fragancia suave y fresca. Presentación 500ml con dispensador.',
                'category_id' => $higiene?->id ?? 6,
                'supplier_id' => $supplier1?->id ?? 1,
                'cost' => 8.00,
                'sellingprice' => 15.00,
                'discount' => 0,
                'price' => 15.00,
                'qty' => 60,
                'total_cost' => 480.00,
                'total_price' => 900.00,
                'published' => 1,
            ],
            [
                'title' => 'Desodorante Roll-On 48h Protección',
                'description' => 'Desodorante roll-on con protección de 48 horas. Controla el sudor y neutraliza olores. Fórmula sin alcohol que no irrita. Fragancia fresca y duradera. Aplicación suave y secado rápido. Presentación 50ml.',
                'category_id' => $higiene?->id ?? 6,
                'supplier_id' => $supplier2?->id ?? 2,
                'cost' => 6.00,
                'sellingprice' => 12.00,
                'discount' => 5,
                'price' => 11.40,
                'qty' => 80,
                'total_cost' => 480.00,
                'total_price' => 912.00,
                'published' => 1,
            ],
            [
                'title' => 'Crema de Afeitar Hidratante',
                'description' => 'Crema de afeitar con aloe vera y vitamina E. Proporciona un afeitado suave y sin irritación. Hidrata durante y después del afeitado. Fórmula enriquecida que protege la piel. Apto para pieles sensibles. Presentación 150ml.',
                'category_id' => $higiene?->id ?? 6,
                'supplier_id' => $supplier3?->id ?? 3,
                'cost' => 10.00,
                'sellingprice' => 20.00,
                'discount' => 8,
                'price' => 18.40,
                'qty' => 40,
                'total_cost' => 400.00,
                'total_price' => 736.00,
                'published' => 1,
            ],

            // COSMÉTICA NATURAL
            [
                'title' => 'Aceite Facial de Rosa Mosqueta Orgánico',
                'description' => 'Aceite facial 100% orgánico de rosa mosqueta. Rico en ácidos grasos esenciales y vitamina A. Regenera la piel, reduce cicatrices y estrías. Hidratación profunda sin dejar sensación grasa. Ideal para pieles maduras y secas. 30ml.',
                'category_id' => $natural?->id ?? 7,
                'supplier_id' => $supplier1?->id ?? 1,
                'cost' => 25.00,
                'sellingprice' => 48.00,
                'discount' => 10,
                'price' => 43.20,
                'qty' => 22,
                'total_cost' => 550.00,
                'total_price' => 950.40,
                'published' => 1,
            ],
            [
                'title' => 'Mascarilla Facial de Miel y Cúrcuma',
                'description' => 'Mascarilla facial natural con miel orgánica y cúrcuma. Ilumina la piel, reduce manchas y acné. Propiedades antibacterianas y antiinflamatorias. 100% ingredientes naturales. Aplicar 2-3 veces por semana. Presentación 100ml.',
                'category_id' => $natural?->id ?? 7,
                'supplier_id' => $supplier2?->id ?? 2,
                'cost' => 16.00,
                'sellingprice' => 32.00,
                'discount' => 12,
                'price' => 28.16,
                'qty' => 28,
                'total_cost' => 448.00,
                'total_price' => 788.48,
                'published' => 1,
            ],
            [
                'title' => 'Exfoliante Corporal de Azúcar y Coco',
                'description' => 'Exfoliante corporal natural con azúcar de caña y aceite de coco. Elimina células muertas y suaviza la piel. Hidrata profundamente dejando la piel sedosa. Fragancia natural de coco. Apto para todo tipo de piel. Presentación 250ml.',
                'category_id' => $natural?->id ?? 7,
                'supplier_id' => $supplier3?->id ?? 3,
                'cost' => 14.00,
                'sellingprice' => 26.00,
                'discount' => 0,
                'price' => 26.00,
                'qty' => 35,
                'total_cost' => 490.00,
                'total_price' => 910.00,
                'published' => 1,
            ],
        ];

        foreach ($products as $productData) {
            $product = Product::create([
                'title' => $productData['title'],
                'description' => $productData['description'],
                'category_id' => $productData['category_id'],
                'supplier_id' => $productData['supplier_id'],
                'cost' => $productData['cost'],
                'sellingprice' => $productData['sellingprice'],
                'discount' => $productData['discount'],
                'price' => $productData['price'],
                'qty' => $productData['qty'],
                'total_cost' => $productData['total_cost'],
                'total_price' => $productData['total_price'],
                'published' => $productData['published'],
                'created_date' => now(),
                'updated_date' => now(),
            ]);

            // Opcional: Agregar imagen placeholder (puedes comentar esto si no quieres imágenes)
            // ProductImage::create([
            //     'product_id' => $product->id,
            //     'image' => 'product_images/placeholder.jpg',
            // ]);
        }

        $this->command->info('✅ Se han creado ' . count($products) . ' productos de cosméticos de belleza exitosamente!');
    }
}

